//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAllWords
    {
        public int Id { get; set; }
        public string Engword { get; set; }
        public string RuWord { get; set; }
        public string SinonimRu { get; set; }
        public string SinonimEn { get; set; }
        public string PastSimple { get; set; }
        public string PastPart { get; set; }
        public int numberPart { get; set; }
        public int numberKind { get; set; }
    }
}
